//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_myUI : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean left
        {
            get
            {
                return SteamVR_Actions.myUI_left;
            }
        }
        
        public virtual SteamVR_Action_Boolean right
        {
            get
            {
                return SteamVR_Actions.myUI_right;
            }
        }
        
        public virtual SteamVR_Action_Boolean up
        {
            get
            {
                return SteamVR_Actions.myUI_up;
            }
        }
        
        public virtual SteamVR_Action_Boolean down
        {
            get
            {
                return SteamVR_Actions.myUI_down;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.myUI_menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean choose
        {
            get
            {
                return SteamVR_Actions.myUI_choose;
            }
        }
    }
}
