//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_fantasy : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean shorter
        {
            get
            {
                return SteamVR_Actions.fantasy_shorter;
            }
        }
        
        public virtual SteamVR_Action_Boolean longer
        {
            get
            {
                return SteamVR_Actions.fantasy_longer;
            }
        }
        
        public virtual SteamVR_Action_Boolean myMove
        {
            get
            {
                return SteamVR_Actions.fantasy_myMove;
            }
        }
        
        public virtual SteamVR_Action_Boolean proceed
        {
            get
            {
                return SteamVR_Actions.fantasy_proceed;
            }
        }
        
        public virtual SteamVR_Action_Boolean backward
        {
            get
            {
                return SteamVR_Actions.fantasy_backward;
            }
        }
        
        public virtual SteamVR_Action_Boolean menu
        {
            get
            {
                return SteamVR_Actions.fantasy_menu;
            }
        }
    }
}
